AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  XRPL-Price-Persist-Oracle Metrics. Provides a scheduled function that produces an image that
  cloudfront will serve up for a 'live' price graph of the README at
  https://github.com/yyolk/xrpl-price-persist-oracle

Parameters:
  ImageDomainName:
    Type: String
    Default: imgs.egge.gg

Globals:

  Function:
    Timeout: 3
    MemorySize: 128


Resources:

  OraclePricesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cw_metrics_lambdaedge/
      Handler: app.handler
      Runtime: python3.8
      AutoPublishAlias: live
      Role: !GetAtt OraclePricesFunctionRole.Arn

  OraclePricesFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
        Path: "/"
        ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        Policies:
          - PolicyName: "xrplOracleGetMetricImages"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - cloudwatch:GetMetricWidgetImage
                  Resource: "*"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "AllowLambdaServiceToAssumeRole"
              Effect: "Allow"
              Action: 
                - "sts:AssumeRole"
              Principal:
                Service: 
                  - "lambda.amazonaws.com"
                  - "edgelambda.amazonaws.com"

  CloudwatchMetricWidgetDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref ImageDomainName
        Origins:
        - Id: FakeOrigin
          DomainName: aws.amazon.com
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
        Enabled: 'true'
        Comment: Distribution for serving the graph on the project README, a facade with lambda@edge.
        DefaultRootObject: ""
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: FakeOrigin
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref OraclePricesFunction.Version
          # b2884449-e4de-46a7-ac36-70bc7f1ddd6d = CachingOptimizedForUncompressedObjects
          CachePolicyId: b2884449-e4de-46a7-ac36-70bc7f1ddd6d
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html#attaching-managed-cache-policies
          ViewerProtocolPolicy: https-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref ImageDomainCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

  ImageDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ImageDomainName
      ValidationMethod: EMAIL
      DomainValidationOptions:
        - DomainName: !Ref ImageDomainName
          ValidationDomain: egge.gg
